name: Test and deploy to Surge
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploying to Surge
    steps:
      - uses: actions/checkout@v2
      - name: Set-up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install -g surge
      - run: npm install --force
      - run: npm run build
      - run: surge ./dist ficusjs-docs.surge.sh --token ${{ secrets.SURGE_TOKEN }}
